# NUMPY.RANDOM PACKAGE

## Overal purpose of package

The random module in Numpy package contains many functions for used for generation of random numbers. In order to understand the main purpose of the package, the definition of random number needs to be introduce.

Random numbers are numbers that occur in a sequence such that two conditions are met:

* the values are uniformly distributed over a defined interval or set
* it is impossible to predict future values based on past or present ones.

Random numbers are important in statistical analysis and probability theory (for example for generating data encryption keys, simulating and modeling complex phenomena and for selecting random samples from larger data sets).

Compluters use two main approaches how to generate the random numbers

* Pseudo-Random Number Generators (PRNGs) 
* True Random Number Generators (TRNGs)


### _Pseudo-Random Number Generators (PRNGs)_

PRNGs are algorithms that use mathematical formulae or simply precalculated tables to produce sequences of numbers that appear random. The main features :

    * efficiency (can produce many numbers in short time)
    * deterministic (a given sequence of numbers can be reproduced at a later date if the starting point in the sequence is known)
    * periodic (the sequence will eventually repeat)
    
These characteristics make PRNGs suitable for applications where many numbers are required and where it is useful that the same sequence can be replayed easily. Popular examples of such applications are simulation and modeling applications.

Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

    * BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.
    * Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.


### _True Random Number Generators (TRNGs)_

TRNGs extract randomness from physical phenomena and introduce it into a computer. The examples of physical phenoma can be the vatiations in mouse movements, athmospheric noise, radioactive source...
The characteristics of TRNGs:

    * TRNGs are generally rather inefficient compared to PRNGs, taking considerably longer time to produce numbers.
    * non-deterministic, meaning that a given sequence of numbers cannot be reproduced, although the same sequence may of course occur several times by chance. 
    * non-periodic
    

## “Simple random data” and “Permutations” functions

### _Simple random data

Numpy



### _numpy.random.rand_

  * output are the random values in a given shape, from the uniform distribution over [0,1) _zero inclusive, 1 exclusive_
  


In [16]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as pl

In [2]:
np.random.rand(3,2)

array([[0.01261523, 0.23769335],
       [0.98852396, 0.31310622],
       [0.76616359, 0.46831936]])

In [7]:
np.random.rand(1,2)

array([[0.08213994, 0.08943041]])

In [8]:
np.random.rand(5,5)

array([[0.25791048, 0.19039527, 0.86532037, 0.65729659, 0.98660705],
       [0.37377655, 0.77502369, 0.26720518, 0.71974161, 0.07836666],
       [0.94861041, 0.80470133, 0.6876005 , 0.73347239, 0.88710949],
       [0.49470352, 0.07876595, 0.52092685, 0.32582402, 0.09599647],
       [0.46532934, 0.56144727, 0.42126679, 0.73057525, 0.72278913]])

Shape of array is defined by numbers in brackets, when the first position determines number of lines and second number defines number of samples in one line.

###  _numpy.random.randn_

  * Return a sample (or samples) from the “standard normal” distribution.
  * Generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 

_if no parameters used in brackets, the output is single float number_

In [9]:
np.random.randn()


0.26300396060481607

_the paramenters in brackets defined the shape of array_

In [11]:
np.random.randn(2,2)

array([[ 0.10274788, -1.8277242 ],
       [ 0.03128934, -0.08572541]])

In [12]:
np.random.randn(2,2)+3

array([[4.62623648, 0.46794348],
       [3.17970284, 0.86556566]])

In [13]:
np.random.randn(2,2)+5

array([[6.40575049, 3.58027898],
       [5.90920651, 5.2703873 ]])

In [14]:
np.random.randn(2,2)-5

array([[-4.94532265, -5.22433974],
       [-5.53212596, -4.82643727]])

In [15]:
np.random.randn(2,5)-100


array([[ -99.35233113,  -98.16452814,  -99.5786566 ,  -99.36685091,
        -101.06997115],
       [ -99.45651601,  -99.76039943,  -99.26407584, -100.25179468,
        -100.08461941]])

### _numpy.random.randint_

In [17]:
np.random.randint(2, size=10)

array([1, 0, 1, 0, 0, 0, 1, 1, 0, 1])

In [19]:
np.random.randint(5, size=10)

array([0, 1, 2, 4, 2, 4, 3, 1, 0, 1])

In [20]:
np.random.randint(-5, size=10)

ValueError: Range cannot be empty (low >= high) unless no samples are taken